# Generated by Django 5.2.1 on 2025-07-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('NIK', models.CharField(max_length=20, unique=True)),
                ('voted', models.BooleanField(default=False)),
            ],
        ),
    ]
